### ISSUE TITLE
adding compression flag

### ISSUE THREAD

**Issue by framki** [evertonstz/pyNPS#1]
Hi.
What you think about adding a compression flag for psp iso images to convert them into `.cso` format using `maxcso` or similar software?

**Comment by evertonstz** [comment]
There's no need to add a third binary dependency in order to achieve this, as lusid1's pkg2zip is already able to pack a cso with multiple levels of compression for PSP games. I'll run some tests with pkg2zip in order to add a good wrap for this option in the script.

Thank you for taking the time to suggest enhancements!

**Comment by evertonstz** [comment]
Work is done in this commit cc6657047a88108a3498455c099d618d97672225
It'll be available in the next binary release.
