### ISSUE TITLE
[Support] pkg2zip compiled binary link is down

### ISSUE THREAD

**Issue by vinmir** [evertonstz/pynps#25]
Hello.

I've compiled pkg2zip v2.3 myself by running `sudo make` on the directory with the source files downloaded from the aforementioned release. 25 files were generated, out of which I believe only `pkg2zip` is needed. Is that correct? I moved `pkg2zip` by itself and tested it on a small `.pkg` I had on my computer, and it worked fine. I transferred `pkg2zip` *by itself* to `/home/$USER/.config/pyNPS/lib/` and everything seems to be working fine, but could anyone tell me if the other 24 files are in fact required?

Finally, as stated in the title, the pre-compiled binary is not downloadable anymore, as the file seems to be removed from the hosting service. I don't think it's a problem, it's just as a kind of heads up. I'm still sort of a beginner on Linux, so it's still useful to me to compare your binary `pkg2zip` with mine to know if

1. I did it correctly
2. The other files are needed.

Thanks.

**Comment by evertonstz** [comment]
Last time I compiled pkg2zip on Linux was a long time ago, but I believe all these files generated are just kinda of side product from the compilation process, what you're looking for is the binary called "pkg2zip". Since you already found and tested it against a file and it worked, you have the right binary.

>I'm still sort of a beginner on Linux, so it's still useful to me to compare your binary pkg2zip with mine to know if

My binary was from an older version, version 2.2, so even if the link wasn't dead, it wouldn't be that useful. I think what you can do is try to compile version 2.2 by yourself and checksum it against the sha256 in the [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=pkg2zip-fork) I've created for Arch Linux.

Anyhow, I'll update the PKGBUILD to support version 2.3 and after I do that I'll make sure to post the new checksum here so you can compare against yours.

**Comment by vinmir** [comment]
> what you're looking for is the binary called "pkg2zip"

Oh, then it's how I had done. Thanks either way
