### ISSUE TITLE
[Enchancement] Ability to choose a download location

### ISSUE THREAD

**Issue by vinmir** [evertonstz/pynps#26]
Hi.

Apparently, pyNPS defaults to `~/Downloads/pyNPS` as the download location. I read the documentation and found nothing about being able to change the default directory, so is it possible to implement this feature? pyNPS is great, keep up the good work!

Thanks.

**Comment by evertonstz** [comment]
Yeah, I need to update the README, there are a lot of features that I've documented on release notes but didn't put there in the documentation.
pyNPS uses a config file that's generated automatically on first run, so you probably already have it in your system. Since you're on Linux, it should be at `~/.config/pyNPS/settings.ini`. Inside the file you'll find options to change the main download folder and the folder where the database files are saved.

**Comment by vinmir** [comment]
Thank you, it's good to know such a feature has already been implemented.
