### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by vrodriguezf** [evertonstz/pynps#5]
Hi, I am having the followig error when executing any `pynps` command:

```
Traceback (most recent call last):
  File "/usr/local/bin/pynps", line 7, in <module>
    from pynps import main
  File "/usr/local/lib/python3.5/dist-packages/pynps.py", line 145
    print(f"Processing {type}: {progress_bar( int(index_file/(len(file) - 1) * 100) )}", 
                                                                                      ^
SyntaxError: invalid syntax
```

I installed it via `pip3` in the Linux installation that is part of ChromeOS. I am in an arm architecture if that may help.

Thanks!

**Comment by Doctus** [comment]
That installation appears to provide Python 3.5, but pyNPS requires Python 3.7 or newer. 

The specific error is because that line contains a formatted string literal, which was introduced in Python 3.6 ([PEP 498](https://www.python.org/dev/peps/pep-0498/)).

If your distribution doesn't provide a newer package (perhaps named `python3.7` or something similar), you might want to use [virtualenv](https://pypi.org/project/virtualenv/) or [pyenv](https://github.com/pyenv/pyenv) to avoid conflicts with the system python.

**Comment by evertonstz** [comment]
As @Doctus said and as specified on the README.md you're required to use python 3.7 or newer, @Doctus gave the best way to solve this problem, but you can also use [the latest linux 64bits binary](https://github.com/evertonstz/pynps/releases/download/1.4.1/pynps-1.4.1-1.x86_64.linux) if you don't want to mess around with python versions and dependencies. Just use it as any other binary and you'll be set.
